name: todo-list

services:
  todo-list-web:
    container_name: todo-list-web
    image: sagarvariya4/todo-list-web:latest
    ports:
      - 3000:3000
    build:
      context: github.com/Sagar-v4/todo-list-webapp
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3001
    restart: always
    networks:
      - app-network
    depends_on:
      - todo-list-server
  todo-list-server:
    container_name: todo-list-server
    image: sagarvariya4/todo-list-server:latest
    ports:
      - 3001:3000
    environment:
      - MONGODB_URI=mongodb://db:27017/todo-list-db?retryWrites=true&w=majority
    build:
      context: github.com/Sagar-v4/todo-list-server
      dockerfile: Dockerfile
    restart: always
    networks:
      - app-network
    depends_on:
      - todo-list-db
  todo-list-db:
    container_name: todo-list-db
    image: mongo:latest
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
        volume:
          nocopy: true
    ports:
      - 27018:27017
    networks:
      - app-network

volumes:
  mongo-data:
    driver: local

networks:
  app-network:
    driver: bridge
