name: Build and Publish image to Docker Hub

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker compose -f docker-compose.prod.yaml up -d --no-start

      - name: Push image to docker hub
        run: |
          docker login -u sagarvariya4 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push todo-list:latest
