name: Build and Publish image to Docker Hub

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:

  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . 
          file: docker-compose.prod.yaml
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}

      # - name: build docker image
      #   run: docker compose -f docker-compose.prod.yaml up -d

      - name: push image to docker hub
        run: |
          docker login -u sagarvariya4 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
