name: Build and Publish image to Docker Hub

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker compose -f docker-compose.prod.yaml up -d --no-start

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sagarvariya4
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push image to Docker Hub
        run: docker push sagarvariya4/todo-list:latest
